name: Auto Label PRs

on:
  pull_request:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description for keywords and add labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = {
              "New Grant Application": "application",
              "Milestone Update": "milestone",
              "Final Report": "final-report"
            };
            const prDescription = context.payload.pull_request.body;
            
            for (const [key, label] of Object.entries(labels)) {
              if (prDescription.includes(key)) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  labels: [label]
                });
              }
            }
